spring.application.name=rotinaAPP
# ========== BANCO DE DADOS ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/rotina_db
spring.datasource.username=postgres
spring.datasource.password=

# ========== JPA / HIBERNATE ==========
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========== FLYWAY ==========
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ========== JWT ==========
app.jwt.secret=minha-chave-secreta-temporaria-trocar-em-producao
app.jwt.expiration-ms=86400000

# ========== SERVIDOR ==========
server.port=8080

